@startuml
scale 350 width
[*] --> Parado : Inicia

Parado --> Subindo : RequisicaoSubir
Parado --> Descendo : RequisicaoDescer

Subindo --> Parado : ChegouAoAndar
Subindo --> Descendo : RequisicaoDescer

Descendo --> Parado : ChegouAoAndar
Descendo --> Subindo : RequisicaoSubir
@enduml
